# Generated by Django 5.0.1 on 2024-01-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_message_post_like_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudusers',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='website/static/users_data/profile_pics/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='website/static/users_data/post_images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='website/static/users_data/post_videos/'),
        ),
    ]
